version: "3.9"
services:

  expense-tracker-api:
    build: .
    container_name: expense-tracker-api
    image: fasilkp/expense-tracker-api:v1.0
    ports:
      - "7000:7000"
    restart: always
    env_file:
      - .env